# -*- #################
# ---------------------------------------------------------------------------
# Basic_wFill_test.py
# Created on: 2018-11-09 13:15:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Basic_wFill_test <Project> <Output_Iteration> <Input_Surface__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
arcpy.env.workspace = arcpy.GetParameterAsText(0)
arcpy.env.overwriteOutput = True

# Script arguments

Project = arcpy.GetParameterAsText(1)
if Project == '#' or not Project:
    Project = "<ProjectName>" # provide a default value if unspecified

Iter = arcpy.GetParameterAsText(2)
##if Output_Iteration == '#' or not Output_Iteration:
##    Output_Iteration = "<IterationNumber>" # provide a default value if unspecified
##
underscore = "_"
DEM = arcpy.GetParameterAsText(3)
zlimit = arcpy.GetParameterAsText(4)
ischecked = arcpy.GetParameterAsText(5)

# Local variables:
##Fill_out = "fill_test"
Fill = Project + underscore + Iter + "_Fill"
Output_drop_raster = ""
FloDir = Project + underscore + Iter + "_FloDir"
FloAcc = Project + underscore + Iter + "_FloAcc"
Sinks = Project + underscore + Iter + "_sink"
Hillshade_filled = Project + underscore + Iter + "_hillshade"
##Raster_gdb = "E:\\Nov18\\Outputs.gdb"

if str(ischecked) == 'true':
    arcpy.AddMessage("Run Fill before FlowDirection")
    # Process: Fill (2)
    arcpy.gp.Fill_sa(DEM, Fill, zlimit)

else:
    arcpy.AddMessage("Not running Fill before FlowDirection")
    Fill = DEM

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(Fill, FloDir, "NORMAL", Output_drop_raster)   

# Process: Flow Accumulation
arcpy.AddMessage("Running Flow Accumulation")
arcpy.gp.FlowAccumulation_sa(FloDir, FloAcc, "", "FLOAT")

# Process: Sink
arcpy.AddMessage("Running Sink")
arcpy.gp.Sink_sa(FloDir, Sinks)

# Process: Hillshade
arcpy.AddMessage("Running Hillshade")
arcpy.gp.HillShade_sa(Fill, Hillshade_filled, "315", "45", "NO_SHADOWS", "1")











