# -*- #################
# ---------------------------------------------------------------------------
# Catchment Artificial Stream Network Model Builder code.py
# Created on: 2018-11-13 16:03:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Catchment Artificial Stream Network Model Builder code <Input_Surface> <Input_Flow_Direction> <Input_Flow_Accumulation> <Stream_Value___1> <Stream_Raster> <StreamLink_Output> <Watershed_Raster> <Watershed_Polygons> <Stream_Polylines> 
# Description: 
# Updated at 03/01/2019 using ArcMap 10.6.1
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *


# Script arguments
Input_Surface = arcpy.GetParameterAsText(0)
Input_Flow_Direction = arcpy.GetParameterAsText(1)
Input_Flow_Accumulation = arcpy.GetParameterAsText(2)
FloAccDivider = arcpy.GetParameterAsText(3)
FloAccDivider = "Value < " + FloAccDivider
Stream_Value___1 = "1"
Prjname = arcpy.GetParameterAsText(5)+ "_" + arcpy.GetParameterAsText(6)

# Set Geoprocessing environments
arcpy.env.snapRaster = Input_Surface
arcpy.env.extent = Input_Surface
arcpy.env.cellSize = Input_Surface
arcpy.env.mask = Input_Surface
arcpy.env.workspace = arcpy.GetParameterAsText(4)
arcpy.env.overwriteOutput = True

# Check out the ArcGIS Spatial Analyst extension license
arcpy.CheckOutExtension("Spatial")


# Local variables:
Watershed_Polygons_out = Prjname + "_Catchments"
Watershed_Raster_out = Prjname + "_Watershed"


# Process: Set Null
arcpy.AddMessage("Running Set Null")
Stream_Raster = SetNull(Input_Flow_Accumulation, Stream_Value___1, FloAccDivider)

# Process: Stream to Feature
arcpy.AddMessage("Running Stream to Feature")
Stream_Polylines = StreamToFeature(Stream_Raster, Input_Flow_Direction, "SIMPLIFY")

# Process: Stream Link
arcpy.AddMessage("Running Stream Link")
StreamLink_Output = StreamLink(Stream_Raster, Input_Flow_Direction)

# Process: Watershed
arcpy.AddMessage("Running Watershed")
Watershed_Raster = Watershed(Input_Flow_Direction, StreamLink_Output, "VALUE")
#Watershed_Raster.save(Watershed_Raster_out)

# Process: Raster to Polygon
arcpy.AddMessage("Running Raster to Polygon")
arcpy.RasterToPolygon_conversion(Watershed_Raster,Watershed_Polygons_out, "SIMPLIFY", "VALUE")

Cellsize = arcpy.GetRasterProperties_management(Watershed_Raster, "CELLSIZEX")
Cellsize = float(str(Cellsize.getOutput(0)))
Arealimit = str(10*Cellsize * Cellsize) 
Queryarea = "Shape_Area <= " + Arealimit

#Find the smallest polygon size
pol_values = [row[0] for row in arcpy.da.SearchCursor(Watershed_Polygons_out,"SHAPE@AREA" )]
min_values = min(pol_values)

cn = 0
eli_names = []

while min_values < float(Arealimit):
    arcpy.MakeFeatureLayer_management (Watershed_Polygons_out, "polylyr")
    arcpy.SelectLayerByAttribute_management("polylyr", "NEW_SELECTION", Queryarea)
    cn = cn + 1
    arcpy.Eliminate_management("polylyr","Eli"+"_"+str(cn))
    Watershed_Polygons_out = "Eli"+"_"+str(cn)
    eli_names.append(Watershed_Polygons_out)

    pol_values = [row[0] for row in arcpy.da.SearchCursor(Watershed_Polygons_out,"SHAPE@AREA" )]
    min_values = min(pol_values)


arcpy.Delete_management(Prjname + "_Catchments")

# Process: Dissolve
arcpy.Dissolve_management(Watershed_Polygons_out, Prjname + "_Catchments", "gridcode")

#arcpy.Rename_management(Watershed_Polygons_out, Prjname + "_Catchments","FeatureClass")

for name in eli_names:
    arcpy.Delete_management(name)


                           






















































