# ---------------------------------------------------------------------------
# CTI_raw.py
# Created on: 2019-02-19 13:24:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: CTI_raw <Input_Filled_DEM> <TanSlopeRad> <Output_Slope> <NoZeros> <CTI> <Input_Flowacc> 
# Description: 
# UPDATED AT 03/01/2019 using 10.6.1
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy import env
from arcpy.sa import *

arcpy.env.workspace = arcpy.GetParameterAsText(0)
arcpy.env.overwriteOutput = True
arcpy.env.cellSize = arcpy.GetParameterAsText(3)

# Check out the ArcGIS Spatial Analyst extension license
arcpy.CheckOutExtension("Spatial")

# Script arguments

Project = arcpy.GetParameterAsText(1)
if Project == '#' or not Project:
    Project = "<ProjectName>" # provide a default value if unspecified

Iter = arcpy.GetParameterAsText(2)

DEM = arcpy.GetParameterAsText(3)
FloAcc = arcpy.GetParameterAsText(4)
Cellsize = arcpy.GetRasterProperties_management(DEM, "CELLSIZEX")

# Local variables:
Input_true_raster_or_constant_value = "0.0001"


# Process: Slope
arcpy.AddMessage("Running Slope")
Output_Slope = Slope(DEM)


# Process: Raster Calculator
arcpy.AddMessage("Running Raster Calculator")
TanSlopeRad = Tan((Output_Slope*1.570796)/90)


# Process: Con
arcpy.AddMessage("Running Con")
outCon = Con(TanSlopeRad, Input_true_raster_or_constant_value,TanSlopeRad, "VALUE = 0")


# Process: Raster Calculator (2)
arcpy.AddMessage("Running Raster Calculator")
CTI = Ln(Times(Raster(FloAcc)+1, float(Cellsize.getOutput(0)))/outCon)
CTI.save(Project + "_" + Iter +"_" +"CTI")






